module.exports = [
  'Wubba-lubba-dub-dub!',
  'Rikki-Tikki-Tavi, biatch!',
  'And that\'s the waaaaay the news goes!',
  'Hit the sack, Jack!',
  'Uh-oh, somersault jump!',
  'AIDS!',
  'And that\'s why I always say, shum-shum-schlippety-dop!',
  'No jumpin\' in the sewer!',
  'Rubber baby bubby bunkers!',
  'Lick, lick, lick my balls! Ha ha ha, yeah! Say that all the time!',
  'Get off the high road. We all got pink eye because you won\'t stop texting on the toilet.',
  'We\'ve got a lot of friends and family to exterminate. ',
  'Uncertainty is inherently unsustainable. Eventually, everything either is or isn\'t.',
  'Stupid-ass, fart-saving, carpet-store motherfucker.',
  'Allah euuh... Akbar! We\'re gonna take control of this plane! We\'re gonna 9/11 it unless Morty Smith gets better grades in math! ',
  'Pickle Riiick!',
  'Get Schwifty',
];
